version: '3.5'
services:
  todo-list.tasks.mongo:
    image: mongo
    restart: always
    container_name: todo-list.tasks.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD

    ports:
      - $MONGO_PORT:27017

    volumes:
      - todo-list.tasks.mongo:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh $MONGO_HOST:$MONGO_PORT/$MONGO_DB --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  todo-list.tasks.mongo.ui:
    image: mongo-express
    restart: always
    container_name: todo-list.tasks.mongo.ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_USER:$MONGO_PASSWORD@$MONGO_NAME:27017/
    depends_on:
      - todo-list.tasks.mongo

volumes:
  todo-list.tasks.mongo:
